apiVersion: v1
kind: Service
metadata:
  name: flexforgeapp-service
  namespace: flexforge_ns
spec:
  selector:
    app: flexforgeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
